
resources:
  - name: S_PS_UTIL_0072
    type: GitRepo
    configuration:
      gitProvider: RahuljGithub
      path: rahulnlb1/pws_jfrog_test
      branches:
        include: master

pipelines:
  - name: pipeline_S_PS_UTIL_0072
    steps:
      - name: S_PS_UTIL_0072
        type: PowerShell
        configuration:
          nodePool: win_2019
          # outputResources:
          #   - name: outgoing
          inputResources:
            - name: S_PS_UTIL_0072
        execution:
          onExecute:
            - $out = new-object byte[] 1048576; (new-object Random).NextBytes($out); [IO.File]::WriteAllBytes('output.dat', $out)
            - add_run_files output.dat my_state
            
      - name: S_PS_UTIL_0072_2
        type: PowerShell
        configuration:
          nodePool: win_2019
          # outputResources:
          #   - name: outgoing
          inputSteps:
            - name: S_PS_UTIL_0072
        execution:
          onExecute:
            - restore_run_files my_state output.dat
